spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Student
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
